# Generated by Django 6.0.3 on 2026-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='dificultad_ejercicio',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=50),
        ),
    ]
