# Generated by Django 6.0.3 on 2026-04-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_ejercicio_dificultad_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intento',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='estudiantes.ejercicio'),
        ),
        migrations.CreateModel(
            name='Aprender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_aprender', models.TextField()),
                ('ejercicioBien_aprender', models.TextField()),
                ('ejercicioMal_aprender', models.TextField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.ejercicio')),
            ],
        ),
    ]
