# Generated by Django 6.0.3 on 2026-05-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_intento_ejercicio_aprender'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprender',
            name='ejercicioJava_aprender',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='estudiantes.tema'),
        ),
    ]
