# Generated by Django 6.0.3 on 2026-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_aprender_ejerciciojava_aprender_alter_ejercicio_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='archivo_pdf_ejercicio',
            field=models.FileField(blank=True, null=True, upload_to='apes/'),
        ),
    ]
