# Generated by Django 6.0.3 on 2026-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_ejercicio_archivo_pdf_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='codigo_ejercicio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='solucion_esperada_ejercicio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
